version: '2'
services:
  php:
      build: ./docker/images/php/
      container_name: market-php
      environment:
        TIMEZONE: ${TIMEZONE}
      env_file: .env
      volumes:
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
        - ./:/var/www/app:cached
      working_dir: /var/www/app
      user: www-data
      networks:
        - back

  web:
    image: nginx:latest
    env_file: .env
    container_name: market-nginx
    ports:
    ## BEGIN webserver_ports ##
      - "${HTTP_BINDED_PORT}:80"
      - "${HTTPS_BINDED_PORT}:443"
    ## END webserver_ports ##
    tty: true
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./docker/config/nginx/ssl:/etc/nginx/ssl
      # - ./docker/config/nginx/auth:/etc/nginx/auth
      - ${NGINX_CONFIG_FILE}:/etc/nginx/sites-enabled/default.conf
      - ./docker/volumes/nginx/logs:/var/log/nginx
    networks:
      - back

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: market-mysql
    env_file: .env
    ports:
      - "${DATABASE_BINDED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "./docker/volumes/mysql:/var/lib/mysql"
    networks:
      - back

networks:
  back:
    driver: bridge